services:

  grafana:
    image: grafana/grafana:latest
    container_name: srv-grafana
    restart: always

    ports:
      - "3000:3000"

    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app

    volumes:
      - grafana-data:/var/lib/grafana


volumes:

  grafana-data:
