services:

  cadvisor:

    image: gcr.io/cadvisor/cadvisor:latest

    container_name: srv-cadvisor

    restart: unless-stopped

    ports:
      - "8082:8080"

    privileged: true

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
